name: Issue Responder
on:
  issues:
    types: [opened]
jobs:
  respond:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check labels and comment
        uses: actions/github-script@v6
        with:
          script: |
            const labels = context.payload.issue.labels.map(l => l.name);
            const owner = context.repo.owner;
            let comment = '';
            if (labels.includes('bug')) {
              comment = `Thank you. We will fix it. Best regards, ${owner}.`;
            } else if (labels.includes('feature')) {
              comment = `Thank you, we will consider to include this feature. Best regards, ${owner}.`;
            } else if (labels.includes('discussion')) {
              comment = `Happy to discuss this topic with you. Best regards, ${owner}.`;
            } else {
              comment = 'Hello, world!';
            }
            if (comment) {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            }